// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"devops.aishu.cn/AISHUDevOps/AnyRobot/_git/itops-alert-manager/server/adapter/controller"
	"devops.aishu.cn/AISHUDevOps/AnyRobot/_git/itops-alert-manager/server/adapter/repository"
	"devops.aishu.cn/AISHUDevOps/AnyRobot/_git/itops-alert-manager/server/adapter/restapi/alert_analysis"
	"devops.aishu.cn/AISHUDevOps/AnyRobot/_git/itops-alert-manager/server/adapter/restapi/isf"
	"devops.aishu.cn/AISHUDevOps/AnyRobot/_git/itops-alert-manager/server/adapter/restapi/knowledge_network"
	"devops.aishu.cn/AISHUDevOps/AnyRobot/_git/itops-alert-manager/server/adapter/restapi/uniquery"
	"devops.aishu.cn/AISHUDevOps/AnyRobot/_git/itops-alert-manager/server/core"
	"devops.aishu.cn/AISHUDevOps/AnyRobot/_git/itops-alert-manager/server/domain/service"
	"devops.aishu.cn/AISHUDevOps/AnyRobot/_git/itops-alert-manager/server/infrastructure/db"
)

// Injectors from wire.go:

func initServer() *core.RouterQuote {
	db := db.NewDBAccess()
	configRepo := repository.NewConfigRepo(db)
	validate := controller.NewValidator()
	httpClient := uniquery.NewHTTPClient()
	uniQueryClient := uniquery.NewUniQueryClient(httpClient)
	alertAnalysisClient := alert_analysis.NewAlertAnalysisClient()
	userManagementClient := isf.NewUserManagementClient()
	knowledgeNetworkClient := knowledge_network.NewKnowledgeNetworkClient()
	aesService := service.NewAesService()
	configService := service.NewConfigService(configRepo,aesService)
	problemService := service.NewProblemService(uniQueryClient, alertAnalysisClient, userManagementClient,knowledgeNetworkClient,configService)
	authVerifyService := service.NewAuthVerifyService()
	problemController := controller.NewProblemController(validate, problemService, authVerifyService)
	configController := controller.NewConfigController(validate,authVerifyService, configService)
	httpRouter := controller.NewHandlerRoute(problemController,configController)
	routerQuote := controller.NewRouterQuote(httpRouter)
	return routerQuote
}
